# The name of the class containing the "main" routine
MAINCLASS=SimpleWebServer

CLASSPATH=.:webserve.jar

build:
	javac -g -cp ${CLASSPATH} *.java

run: build
	java -ea -cp ${CLASSPATH} ${MAINCLASS}

clean:
	rm -f *.class

